packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/expo": ^1.1.19
  "@tanstack/react-query": ^5.64.0
  "@trpc/client": ^11.0.0-rc.802
  "@trpc/react-query": ^11.0.0-rc.802
  "@trpc/server": ^11.0.0-rc.802
  better-auth: ^1.1.19
  devalue: ^5.1.1
  eslint: ^9.14.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2
